### ISSUE TITLE
gnng: Fail Gracefully if Device Can't be Found

### ISSUE THREAD

**Issue by supertylerc** [trigger/trigger#278] opened 2016-04-18 17:02 UTC
`gnng` should fail gracefully if it can't find a device.

```
$ gnng 10.254.254.254
Traceback (most recent call last):
  File "/Users/tylerchristiansen/.virtualenvs/trigger/bin/gnng", line 461, in <module>
    main()
  File "/Users/tylerchristiansen/.virtualenvs/trigger/bin/gnng", line 445, in main
    routers = fetch_router_list(args[1:])
  File "/Users/tylerchristiansen/.virtualenvs/trigger/bin/gnng", line 95, in fetch_router_list
    if not pass_filters(nd.find(arg)):
  File "/Users/tylerchristiansen/.virtualenvs/trigger/lib/python2.7/site-packages/trigger/netdevices/__init__.py", line 872, in find
    raise KeyError(key)
KeyError: '10.254.254.254'
```

**Comment by jathanism** [comment] 2016-04-18 17:03
Dupe of https://github.com/trigger/trigger/issues/89

**Closed by jathanism** 2016-04-18 17:03 UTC
Labels: duplicate
